workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_train"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - when: never

include:
  - local: "auto-devops/main/*.yml"
    rules:
      - if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == "main"'

  - local: "auto-devops/staging/*.yml"
    rules:
       - if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == "staging"'

  - local: "auto-devops/develop/*.yml"
    rules:
      - if: '$CI_COMMIT_TAG || ($CI_COMMIT_REF_NAME !~ /^(main|staging)$/)'


stages:
  - prepare
  - build-and-push
  - test
