include:
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.prepare-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.uv-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.build-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.test-gitlab-ci.yml'
    ref: 'main'
  - project: 'sales-trigger/sdk/gitlab-ci-cd'
    file: '.postpipeline-gitlab-ci.yml'
    ref: 'main'


variables:
  PACKAGE_PUBLISH: "uv"
  TEST_GROUP: "python-full"
  LINT: "ruff"